Первое задание
GeorgeTim1998/test-guru pull request #1
Opened 2022-01-18 11:00 UTC by GeorgeTim1998

2022-01-18 17:00 UTC, VidgarVii requested changes

2022-01-18 17:00 UTC, VidgarVii commented on README.md
> +* Публикатор результатов теста в соц сети
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2022-01-18 17:00 UTC, VidgarVii commented on config/application.rb
> +    config.active_record.default_timezone = :local
```
config.active_record.default_timezone = :local
```

так делать не рекомендуется (`default_timezone = :local`)

стандарт - хранение времени в UTC
это намного удобнее для приложений, в которых используется несколько таймзон (приложение всегда может стать таким)

2022-01-18 17:00 UTC, VidgarVii commented on config/initializer.rb
> +VERSION = '1.0.0-alpha'.freeze
не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложение (9-я строка)

```ruby
module TestGuru
  class Application < Rails::Application
    VERSION = '0.1.0'.freeze
  end
end
```

2022-01-18 17:00 UTC, VidgarVii commented on config/initializer.rb
> +VERSION = '1.0.0-alpha'.freeze
для мажора слишком рано. Максимум на что можно рассчитывать это минор. Перечитай документацию semver.org
alpha тоже еще нет

2022-01-18 17:00 UTC, VidgarVii commented on public/about/author/aboutme.html
> +    <a href="https://github.com/GeorgeTim1998/test-guru"> GitHub </a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-01-18 17:00 UTC, VidgarVii commented on public/about/author/aboutme.html
> +  <head>
самый главный тек <html> забыл.
Обязательно подтяни html

2022-01-19 10:18 UTC, GeorgeTim1998 commented on config/application.rb
> +    config.active_record.default_timezone = :local
done

2022-01-19 10:21 UTC, GeorgeTim1998 commented on config/initializer.rb
> +VERSION = '1.0.0-alpha'.freeze
done

2022-01-19 14:17 UTC, VidgarVii requested changes

2022-01-19 14:17 UTC, VidgarVii commented on config/application.rb
> +    config.active_record.default_timezone = :local
не исправил

2022-01-19 14:17 UTC, VidgarVii commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
версия ПО не является настройкой
у тебя до этого было почти правильно
версию определяют именно в config/initializers
вот [посмотри](https://github.com/plataformatec/devise/blob/master/lib/devise/version.rb) как гем `Devise` хранит свою версию - это стандартный вариант для руби-гемов

а вот [пост](https://alexpeattie.com/blog/defining-versions-in-ruby-gems) про версификацию руби-гемов
посмотри на пример кода с патчем, где идет проверка версии `Devise`
удобно обращаться не просто ко вселенной - `VERSION`, а к конкретному модулю - `Devise::VERSION`
если вдруг код будет подразумевать необходимость использования версий нескольких модулей, то без неймспейсинга совсем не ясно, как разруливать ситуацию

аналогично нужно реализовать и здесь
только модуль конечно не `Devise` будет, а имя твоего приложения (посмотри для примера в файл `config/application.rb`, где ты добавляешь локаль и таймзон, там эти строки конфигурации помещены внутрь модуля твоего приложения)

2022-01-19 14:19 UTC, VidgarVii requested changes

2022-01-19 14:19 UTC, VidgarVii commented on public/about/author/aboutme.html
> +    target="_blank">GitHub</a>
не надо всё в 1 столбик писать.

2022-01-19 14:19 UTC, VidgarVii commented on public/about/author/aboutme.html
> +    <hi>Ссылка на</hi>
`<hi>` это что-то новое...

2022-01-23 11:04 UTC, VidgarVii requested changes

2022-01-23 11:04 UTC, VidgarVii commented on .rubocop.yml
> +  Enabled: false
всегда нужен указатель на конец файла в виде пустой строки

2022-01-23 11:04 UTC, VidgarVii commented on .gitignore
> +.vscode
всегда нужен указатель на конец файла в виде пустой строки

2022-01-23 11:04 UTC, VidgarVii commented on config/application.rb
> +    config.active_record.default_timezone = :utc
default_timezone вообще можно не трогать. Пусть работает как есть

2022-01-23 11:04 UTC, VidgarVii commented on public/about/author/aboutme.html
> +</html>
всегда нужен указатель на конец файла в виде пустой строки

2022-01-23 11:04 UTC, VidgarVii commented on public/about/project.html
> +</html>
всегда нужен указатель на конец файла в виде пустой строки

2022-01-26 19:57 UTC, merged