Proper beginning
GeorgeTim1998/test-guru pull request #2
Opened 2022-01-28 20:27 UTC by GeorgeTim1998

2022-01-29 10:59 UTC, VidgarVii requested changes

2022-01-29 10:59 UTC, VidgarVii commented on config/database.yml
> +  database: my_development
было хорошее понятное название для базы. Потом и не вспомнишь что база my_development

2022-01-29 10:59 UTC, VidgarVii commented on db/migrate/20220128193944_add_questions_test_id__null_constraint.rb
> +    change_column_null(:questions, :test_id, false)
не надо добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2022-01-29 10:59 UTC, VidgarVii commented on db/migrate/20220128202151_add_default_correct_to_answer.rb
> +end
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

тут мы укажем, что поле должно быть обязательно заполнен и обеспечим ссылочную целостность данных, через внешний ключ
[внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)


Тест принадлежит Категории и Автору
Тест имеет Вопросы
Вопросы имеют Ответы

2022-01-30 19:23 UTC, GeorgeTim1998 commented on config/database.yml
> +  database: my_development
DONE

2022-01-31 07:40 UTC, VidgarVii requested changes

2022-01-31 07:40 UTC, VidgarVii commented on db/migrate/20220128152138_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
лучше чтобы поле в таблице называлось author_id.
Так как по логике нам надо создать ассоциацию как автор теста
т.е. получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2022-01-31 07:40 UTC, VidgarVii commented on db/migrate/20220128152138_create_tests.rb
> +      t.string :title, null: false, from: nil, to: 1
тут явно ошибка с from: nil, to: 1

2022-01-31 07:40 UTC, VidgarVii commented on db/migrate/20220128194412_create_answers.rb
> +      t.string :correct, null: false, from: nil, to: '1'
поле `correct` может по сути иметь только 2 значния "да" или "нет"
когда поле подразумевает только 2 значения пользуются типом `boolean` (логическое поле, которое может содержать только `true`/`false` значения)

2022-01-31 19:15 UTC, merged